version: "3.9"
   
services:
  frontend:
    image: albums.azurecr.io/aca-frontend:1.0
    environment:
      - API_BASE_URL=http://api:3000
      - BACKGROUND_COLOR=blue
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    image: albums.azurecr.io/aca-node:1.0
    environment:
      - API_BASE_URL=http://api:3000
    expose:
      - "3000"