name: Trigger auto deployment for containerapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'aca-frontend/**'
    - '.github/workflows/gha-aca-frontend-AutoDeployTrigger-09609c64-c298-45d6-9d61-33dd15cfffc4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: antchuacr201907.azurecr.io
          username: ${{ secrets.DEMO_ACA_FRONTEND_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMO_ACA_FRONTEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: antchuacr201907.azurecr.io/gha-aca-frontend:${{ github.sha }}
          file: aca-frontend/Dockerfile
          context: aca-frontend/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMO_ACA_FRONTEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n gha-aca-frontend -g demo --server antchuacr201907.azurecr.io --username  ${{ secrets.DEMO_ACA_FRONTEND_REGISTRY_USERNAME }} --password ${{ secrets.DEMO_ACA_FRONTEND_REGISTRY_PASSWORD }}
            az containerapp update -n gha-aca-frontend -g demo --image antchuacr201907.azurecr.io/gha-aca-frontend:${{ github.sha }}
