name: Deploy to gha-aca-csharp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'aca-csharp/**'
    - '.github/workflows/gha-aca-csharp-AutoDeployTrigger-06e66706-9b70-4494-a84a-fa1fc570d929.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: antchuacr201907.azurecr.io
          username: ${{ secrets.DEMO_ACA_CSHARP_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMO_ACA_CSHARP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: antchuacr201907.azurecr.io/gha-aca-csharp:${{ github.sha }}
          file: aca-csharp/Dockerfile
          context: aca-csharp/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMO_ACA_CSHARP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n gha-aca-csharp -g demo --server antchuacr201907.azurecr.io --username  ${{ secrets.DEMO_ACA_CSHARP_REGISTRY_USERNAME }} --password ${{ secrets.DEMO_ACA_CSHARP_REGISTRY_PASSWORD }} --debug
            az containerapp update -n gha-aca-csharp -g demo --image antchuacr201907.azurecr.io/gha-aca-csharp:${{ github.sha }}
